title: Oscar Talavera
description: Sitio personal de Oscar Talavera
baseurl: ""
url: "https://oscartalavera.com"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuración de colecciones
collections:
  recetas:
    output: true
    permalink: /recetas/:title/
  coches:
    output: true
    permalink: /coleccion/:title/

# Configuración por defecto para recetas
defaults:
  - scope:
      path: ""
      type: "recetas"
    values:
      layout: "recipe"
      author: "Oscar Talavera"
  - scope:
      path: ""
      type: "coches"
    values:
      layout: "car"
      author: "Oscar Talavera"
